-- AlterTable
ALTER TABLE "image" ALTER COLUMN "description" SET DATA TYPE VARCHAR(256);

-- AlterTable
ALTER TABLE "user" ALTER COLUMN "hash" SET DATA TYPE VARCHAR(256),
ALTER COLUMN "salt" SET DATA TYPE VARCHAR(256);
